### ISSUE TITLE
error when showing recipes

### ISSUE THREAD

**Issue by FKuerten** [NSkelin/Transportorio#1]
Pretty fresh map without any other mods:
When I click on the "Trades" button the map crashes.

```
The mod Transportorio (0.0.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Transportorio::on_lua_shortcut (ID 36)
__Transportorio__/control.lua:1044: attempt to call method 'toggle' (a nil value)
stack traceback:
	__Transportorio__/control.lua:1044: in function <__Transportorio__/control.lua:1041>
```

**Comment by NSkelin** [comment]
Was this a multiplayer game? I cant replicate it in singleplayer

**Comment by NSkelin** [comment]
https://github.com/NSkelin/Transportorio/commit/a09637031711820522cb17201c173c7ea95fcb49

**Comment by FKuerten** [comment]
It was in single player.
But I can no longer reproduce this in the latest version.
Thank you.
